# Generated by Django 3.2.15 on 2023-05-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'files', 'verbose_name_plural': 'files'},
        ),
    ]
