# Generated by Django 3.2.15 on 2023-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.ImageField(null=True, upload_to='files/'),
        ),
    ]
