# Generated by Django 3.2.15 on 2023-05-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_initiator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('expired', models.DateTimeField()),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'tasks',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
