# Generated by Django 3.2.15 on 2023-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'support', 'verbose_name_plural': 'support'},
        ),
        migrations.AlterField(
            model_name='support',
            name='country',
            field=models.CharField(max_length=256),
        ),
    ]
