# Generated by Django 3.2.15 on 2023-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_support_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='happy',
            field=models.BooleanField(default=False),
        ),
    ]
