# Generated by Django 3.2.15 on 2023-05-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stripe_product_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('country', models.CharField(choices=[('RU', 'Россия'), ('US', 'США')], max_length=10, verbose_name='Страна')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('discussion', models.TextField()),
            ],
        ),
    ]
